### ISSUE TITLE
Broken when used with Ember 2.14

### ISSUE THREAD

**Issue by rondale-sc** [stefanpenner/broccoli-concat-analyser#16]
I believe this addon relies on `vendor/ember/ember.debug.map` being present.

![screen shot 2017-08-08 at 1 14 23 pm](https://user-images.githubusercontent.com/75710/29084923-853138ac-7c3b-11e7-99c1-4b4f31f62bf8.png)

There is an outstanding issue here https://github.com/emberjs/ember.js/issues/15464 that I believe is related.  I'm not sure of a workaround atm, but thought this might be a good place to add insight into implications of sourcemaps not being available.

**Comment by simonihmig** [comment]
@rondale-sc not sure if that is really tied to the ember sourcemap issue. The warning is not part of the stack trace, and the trace contains something about `ember-css-modules`...

Also the issue should probably go to either the https://github.com/broccolijs/broccoli-concat repo or `ember-css-modules`, so closing this here.

Btw, just created a PR that should hopefully fix the Ember sourcemap issue here, in case this is related: https://github.com/emberjs/ember.js/pull/15577
