### ISSUE TITLE
Output to SVG?

### ISSUE THREAD

**Issue by NullVoxPopuli** [stefanpenner/broccoli-concat-analyser#28]
Let's say I want to include the very nice bundle analysis in my repo and/or as artifacts on my ci/cd environment..

Is there a way I can output a self-contained file?
at the moment, there aren't many files,
![image](https://user-images.githubusercontent.com/199018/42567797-f593e5ee-84d8-11e8-8b68-b6360daac216.png)
but without zipping, it'd be hard to send this to somebody.

I can screenshot,
![image](https://user-images.githubusercontent.com/199018/42567810-0661b680-84d9-11e8-8db2-4ba9b3ae3291.png)

but I lose the ability to zoom in on the smaller pieces -- so I think an SVG would be _the_ perfect solution to this. :)

**Comment by stefanpenner** [comment]
SVG would be good, although zoom would be lost. An alternative, would be to simply inline everything into the index.html. Which then could be shared?

Thoughts?

**Comment by NullVoxPopuli** [comment]
I think that'd be good enough, since sharing is the goal anyway :D

**Comment by stefanpenner** [comment]
@NullVoxPopuli  maybe like: https://github.com/stefanpenner/broccoli-concat-analyser/pull/29 ?

**Comment by stefanpenner** [comment]
which produces: http://static.iamstef.net/foo.html

**Comment by NullVoxPopuli** [comment]
was that url a temp url?

**Comment by stefanpenner** [comment]
http://static.iamstef.net/self-contained-analyser-output.html

**Comment by NullVoxPopuli** [comment]
Perfection!

**Comment by stefanpenner** [comment]
Thanks for the idea!

**Comment by NullVoxPopuli** [comment]
@stefanpenner this is the best thing :)

https://emberclear.io/bundle.html

thanks again!

**Comment by stefanpenner** [comment]
emberclear looks cool!

**Comment by NullVoxPopuli** [comment]
Thanks!
