### ISSUE TITLE
Improved README.md

### ISSUE THREAD

**Issue by Driezzz** [stefanpenner/broccoli-concat-analyser#35]
Could it possible to improve the current readme? It's not quite clear to me what the steps are to actually get the process output.

> 0 npm install -g broccoli-concat-analyser
> 1 using broccoli-concat (latest versions)
> 2 CONCAT_STATS=true ember s
> 3 broccoli-concat-analyser ./concat-stats-for
> 4 look at .out.json files in ./concat-stats-for for the process output

1 It's a dependency of ember-cli, so I can ignore that probably unless someone doesn't have it installed.
2 Where do you put **CONCAT_STATS=true**. This does not work, I just found out this is a linux style command. I'm on Windows.
3 What does this mean?
4 I can't find the file, probably because I'm not doing it correctly.

**Comment by simonihmig** [comment]
> 1 It's a dependency of ember-cli, so I can ignore that probably unless someone doesn't have it installed.

No, it is not. This package is technically unrelated to Ember. It works using the debug out of `broccoli-concat` which Ember CLI uses.

> 2 Where do you put CONCAT_STATS=true. This does not work, I just found out this is a linux style command. I'm on Windows.

Yes, indeed this is for Linux or Mac. It is an environment variable that needs to be present for `broccoli-concat` to generate the stats output. 

> 3 What does this mean?

You have to run this command (which should have been installed in the first step) to generate the output.

> 4 I can't find the file, probably because I'm not doing it correctly.

After running the command, you should find a `./concat-stats-for/index.html` that you can open in a browser.

I agree the documentation could be better. However I am currently working on wrapping this library in an Ember addon, so it is much easier to consume for Ember users! The repo is here: https://github.com/simonihmig/ember-cli-concat-analyzer. Though that is still work in progress and not yet published.

**Comment by Driezzz** [comment]
Thank you for your time!
