### ISSUE TITLE
group by module paths (to help identify offending addons/areas)

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/broccoli-concat-analyser#4]
so given

* `ember-data/-private/system/store`
* `ember-data/adapters/rest.js`

We could create the following depth:

* `ember-data`
  * `adapters`
    * `rest.js`
  * `-private`
    * `system`
      * `store.js`

Most likely though, merely adding 1 additional grouping (the top level) would drastically improve this.

* `ember-data`
  * `adapters/rest.js`
  * `-private/system/store.js`

**Comment by simonihmig** [comment]
@stefanpenner will try to come up with a PR implementing this, fyi! 

Really useful library btw, I feel this should get much more attention! 👌

**Comment by stefanpenner** [comment]
@simonihmig I would love to get this polished up, so we can include it by default.
