### ISSUE TITLE
"CONCAT_STATS=true ember s" is not generating /concat-stats-for dir

### ISSUE THREAD

**Issue by Exelord** [stefanpenner/broccoli-concat-analyser#48]
CONCAT_STATS=true ember s is not generating /concat-stats-for dir

v4.3.5

**Comment by stefanpenner** [comment]
@Exelord interesting, what version of `ember-cli` ? Is it all apps (even a new one) or just your app?

**Comment by Exelord** [comment]
Oh... so sorry. Its just in my app. Probably some edge case :/

**Comment by stefanpenner** [comment]
@Exelord interesting, if you can share a reproduction (minimal) I'll gladly take a look

**Comment by Exelord** [comment]
The app is huge, it will be hard to reproduce it. But thank you for offering the help :) ❤️

**Comment by oliverlj** [comment]
got this issue too if ember-cli-bundle-analyzer is in package.json on Ember 3.16
